# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'ReactNativeTest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

    pod 'React', :path => '../node_modules/react-native', :subspecs => [
        'Core',
        'DevSupport', # 如果RN版本 >= 0.43，则需要加入此行才能开启开发者菜单
        'RCTText',
        'RCTNetwork',
        'RCTWebSocket', # 这个模块是用于调试功能的
        'BatchedBridge',
        'RCTImage'
    # 在这里继续添加你所需要的模块
    ]
    # 如果你的RN版本 >= 0.42.0，请加入下面这行
    pod "Yoga", :path => "../node_modules/react-native/ReactCommon/yoga"

  # Pods for ReactNativeTest

  target 'ReactNativeTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ReactNativeTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
